### ISSUE TITLE
Support for repos with periods in name

### ISSUE THREAD

**Issue by simshanith** [dgoguerra/parse-repo#1]
I have a repo with a name that includes `.` - [simshanith/pi.simloovoo.com](/simshanith/pi.simloovoo.com). `parse-repo` fails to detect the correct protocol, host, and owner; though repository and project are correct.

```sh
$ node -v
v6.9.1
$ node
```

> ```js
> > require('parse-repo')('git@github.com:simshanith/pi.simloovoo.com.git')
> { remote: 'git@github.com:simshanith/pi.simloovoo.com.git',
>   protocol: 'file',
>   host: 'localhost',
>   owner: null,
>   repository: 'pi.simloovoo.com',
>   project: 'pi.simloovoo.com' }
> ```
> ```js
> > require('parse-repo')('git@github.com:simshanith/pisimloovoocom.git')
> { remote: 'git@github.com:simshanith/pisimloovoocom.git',
>   protocol: 'git',
>   host: 'github.com',
>   repository: 'simshanith/pisimloovoocom',
>   owner: 'simshanith',
>   project: 'pisimloovoocom' }
> ```

**Comment by dgoguerra** [comment]
Published in npm at v1.0.3, thanks!
