### ISSUE TITLE
support ssh://

### ISSUE THREAD

**Issue by jfairley** [dgoguerra/parse-repo#3]
I use the [Jenkins Git Plugin](https://wiki.jenkins.io/display/JENKINS/Git+Plugin). It's documentation includes URL patterns that start with `ssh://` that I've used in the past, but aren't supported here.

Copied from Jenkins Git Plugin documentation:

```
The following are examples of valid git URLs.

-    ssh://git@github.com/org-name/project-name.git
-    git@github.com:org-name/project.git (short notation for ssh protocol)
-    ssh://user@other.host.com/~/repos/R.git (to access the {repos/R.git repository in the user's home directory)
-    https://github.com/github/git.git
-    git://github.com/org-name/project.git
```

Not really a blocker for me. I simply switched my config to `git@...`, but it'd be nice if they were covered.

Thanks for the library!

**Comment by dgoguerra** [comment]
Thank you! I have improved the uris parsing and added more extensive tests, I believe all different formats should be parsed correctly now.

**Comment by jfairley** [comment]
Awesome. Thank you!
